### PR TITLE
Update training.html

### PR DESCRIPTION
**Pull request by brains4math**
Should be "rows", not "columns". Corrected explanation.

### CODE REVIEW

**Comment by zgrkpnr** [comment]
@brains4math  You did wrong. Dataset of hype is a column matrix. Rows are features and columns are training sample. I cannot blame you because the conventional way is samples at each row.

**Comment by brains4math** [comment]
@zgrkpnr This sentence - "The data has 14 rows and 506 columns, where each column represents the 14 features of one house." makes no sense. The first part states that there are 14 rows. The second part refers to 14 columns. I understand that rows are features and columns are training sample, which is why I still think that the second half of the sentence needs to be corrected to refer to 14 row features, not 14 column features, as it currently does.

**Comment by smoothdeveloper** [comment]
@brains4math I think the source file you'd need to fix is there:

https://github.com/hypelib/Hype/blob/master/docs/input/Training.fsx#L91

your modification to the html will be lost when the doc is generated again

**Comment by brains4math** [comment]
Thank you, @smoothdeveloper ! I'm new at this, and if you have any other tips for me I'd be grateful

**Comment by smoothdeveloper** [comment]
@brains4math I think we should close this PR. Also, @zgrkpnr (and the doc) is correct, maybe you'd propose to rephrase it another way:

In this table, each column is an observation (house in our dataset), and each row is a feature (such as area, number of floors, price, etc.) ...

**Pull request closed without merging**
